/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.logicalcontextsimulator.gui;

import javax.swing.JMenuItem;
import javax.swing.JPanel;

import com.logicalcontextsimulator.util.Constants;

/**
 *
 * @author MHL
 */
public class MainFrame extends javax.swing.JFrame {

    /**
	 * 
	 */
	private static final long serialVersionUID = -3319664931640740523L;
	/**
     * Creates new form NewMain
     */
    public MainFrame() {
        initComponents();
        
        jMenuItemLoad.setIcon(Constants.getInstance().getImageIcon(Constants.URL_ICON_OPEN));
        jMenuItemSave.setIcon(Constants.getInstance().getImageIcon(Constants.URL_ICON_SAVE));
        jMenuItemImport.setIcon(Constants.getInstance().getImageIcon(Constants.URL_ICON_IMPORT));
        jMenuItemSettings.setIcon(Constants.getInstance().getImageIcon(Constants.URL_ICON_SETTINGS));
        
        setTitle("Context Simulator");
    }
    
    public JPanel getMainPanel(){
        return jMainPanel;
    }

    public JMenuItem getMenuItemLoad() {
        return jMenuItemLoad;
    }

    public JMenuItem getMenuItemSave() {
        return jMenuItemSave;
    }

    public JMenuItem getMenuItemSettings() {
        return jMenuItemSettings;
    }
    
    public JMenuItem getMenuItemImport() {
        return jMenuItemImport;
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMainPanel = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItemSave = new javax.swing.JMenuItem();
        jMenuItemLoad = new javax.swing.JMenuItem();
        jMenuItemImport = new javax.swing.JMenuItem();
        jMenuItemSettings = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setName("Context Simulator"); // NOI18N
        setPreferredSize(new java.awt.Dimension(800, 550));

        jMainPanel.setMinimumSize(new java.awt.Dimension(400, 400));
        jMainPanel.setName(""); // NOI18N
        jMainPanel.setLayout(new java.awt.BorderLayout());
        getContentPane().add(jMainPanel, java.awt.BorderLayout.CENTER);

        jMenu1.setText("File");

        jMenuItemSave.setText("Save");
        jMenuItemSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemSaveActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemSave);

        jMenuItemLoad.setText("Load");
        jMenu1.add(jMenuItemLoad);

        jMenuItemImport.setText("Import");
        jMenuItemImport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemImportActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemImport);

        jMenuItemSettings.setText("Settings");
        jMenuItemSettings.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemSettingsActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemSettings);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemSaveActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItemSaveActionPerformed

    private void jMenuItemSettingsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemSettingsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItemSettingsActionPerformed

    private void jMenuItemImportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemImportActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItemImportActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jMainPanel;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    public javax.swing.JMenuItem jMenuItemImport;
    private javax.swing.JMenuItem jMenuItemLoad;
    private javax.swing.JMenuItem jMenuItemSave;
    private javax.swing.JMenuItem jMenuItemSettings;
    // End of variables declaration//GEN-END:variables
}
