/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.logicalcontextsimulator.gui.panel.contextList;

import javax.swing.JScrollPane;
import javax.swing.JTree;

/**
 *
 * @author MHL
 */
public class ContextTreePanel extends javax.swing.JPanel {

    /**
	 * 
	 */
	private static final long serialVersionUID = 1145212408388421499L;
	/**
     * Creates new form ContextTree
     */
    public ContextTreePanel() {
        initComponents();
    }

    public JTree getJTree() {
        return jDetailTree;
    }

    public JScrollPane getTreeScrollPane() {
        return jTreeScrollPane;
    }

    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTreeScrollPane = new javax.swing.JScrollPane();
        jDetailTree = new javax.swing.JTree();

        setLayout(new java.awt.BorderLayout());

        javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("Context");
        jDetailTree.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        jDetailTree.setToggleClickCount(1);
        jTreeScrollPane.setViewportView(jDetailTree);

        add(jTreeScrollPane, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTree jDetailTree;
    private javax.swing.JScrollPane jTreeScrollPane;
    // End of variables declaration//GEN-END:variables
}
