/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.logicalcontextsimulator.gui.panel.contextList;

import com.logicalcontextsimulator.model.renderer.MyListCellRenderer;
import javax.swing.BorderFactory;
import javax.swing.border.Border;
import javax.swing.border.TitledBorder;

/**
 *
 * @author MHL
 */
public class CurrentTestCasePanel extends javax.swing.JPanel {

    /**
	 * 
	 */
	private static final long serialVersionUID = -7776524849427224708L;

	private Border detachedBorder;
    
    private TitledBorder titleBorder;
    
    /**
     * Creates new form CurrentTestCasePanel
     */
    public CurrentTestCasePanel() {
        initComponents();
        
        titleBorder = BorderFactory.createTitledBorder(detachedBorder, "Defect Pattern");
        titleBorder.setTitleJustification(TitledBorder.CENTER);
        jPanel1.setBorder(titleBorder);
        
        titleBorder = BorderFactory.createTitledBorder(detachedBorder, "Abstract Test Case");
        titleBorder.setTitleJustification(TitledBorder.CENTER);
        jPanel2.setBorder(titleBorder);
        
        titleBorder = BorderFactory.createTitledBorder(detachedBorder, "Concrete Test Case (Example)");
        titleBorder.setTitleJustification(TitledBorder.CENTER);
        jPanel3.setBorder(titleBorder);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();

        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.LINE_AXIS));

        jPanel1.setLayout(new java.awt.BorderLayout());

        jList1.setModel(new javax.swing.AbstractListModel() {
            /**
			 * 
			 */
			private static final long serialVersionUID = -2825561694385181147L;
			String[] strings = { "Incomplete: Unavailability", "Sensor Noise: Incorectness", "Sensor Noise: False reading", "Sensor Noise: Unreliability", "Slow Sensing: Out-of-Dateness", "Slow Sensing: Wrong interpretation", "Granularity Missmatch: Imprecision" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jList1.setCellRenderer(new MyListCellRenderer());
        jList1.setPreferredSize(new java.awt.Dimension(140, 112));
        jScrollPane1.setViewportView(jList1);

        jPanel1.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        add(jPanel1);

        jPanel2.setLayout(new java.awt.BorderLayout());

        jTextArea1.setEditable(false);
        jTextArea1.setBackground(new java.awt.Color(204, 204, 204));
        jTextArea1.setColumns(20);
        jTextArea1.setLineWrap(true);
        jTextArea1.setRows(5);
        jTextArea1.setText("Example:\nIt is almost impossible, to receive same GPS information at one spot within two requests, because GPS is not exactly.\n\nPre-Condition:\nOne context source transmits data\n\nAction:\nChange the simulated data slightly and send it again\n\nPost-Condition:\nSame context source transmit updated data, even when the actual context has not changed\n");
        jScrollPane2.setViewportView(jTextArea1);

        jPanel2.add(jScrollPane2, java.awt.BorderLayout.CENTER);

        add(jPanel2);

        jPanel3.setLayout(new java.awt.BorderLayout());

        jTextArea2.setEditable(false);
        jTextArea2.setBackground(new java.awt.Color(204, 204, 204));
        jTextArea2.setColumns(20);
        jTextArea2.setLineWrap(true);
        jTextArea2.setRows(5);
        jTextArea2.setText("Pre-Condition:\nSimulator transmits correct GPS data of the company\n\nAction:\nSimulator chooses new GPS-coordinates, which are 100 meters away from the previous coordinates\n\nPost-Condition:\nApplication receives imprecise coordinates\n");
        jScrollPane3.setViewportView(jTextArea2);

        jPanel3.add(jScrollPane3, java.awt.BorderLayout.CENTER);

        add(jPanel3);
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList jList1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    // End of variables declaration//GEN-END:variables
}
