/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.logicalcontextsimulator.gui.panel.contextList;

import javax.swing.JTextArea;

/**
 *
 * @author MHL
 */
public class CurrentTransmissionPanel extends javax.swing.JPanel {

    /**
	 * 
	 */
	private static final long serialVersionUID = 8005831631627009988L;
	/**
     * Creates new form CurrentTransmissionPanel
     */
    public CurrentTransmissionPanel() {
        initComponents();
    }

    public JTextArea getTaCurrentTransmission() {
        return taCurrentTransmission;
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        taCurrentTransmission = new javax.swing.JTextArea();

        setLayout(new java.awt.BorderLayout());

        taCurrentTransmission.setEditable(false);
        taCurrentTransmission.setColumns(15);
        taCurrentTransmission.setRows(5);
        jScrollPane1.setViewportView(taCurrentTransmission);

        add(jScrollPane1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea taCurrentTransmission;
    // End of variables declaration//GEN-END:variables
}
