/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.logicalcontextsimulator.gui.panel.contextList;

import javax.swing.DefaultComboBoxModel;
import javax.swing.JList;
import javax.swing.JScrollPane;

import com.logicalcontextsimulator.model.renderer.MyListCellRenderer;

/**
 *
 * @author MHL
 */
public class ListPanelSituation extends javax.swing.JPanel {

    /**
	 * 
	 */
	private static final long serialVersionUID = -6817295831630477770L;
	private DefaultComboBoxModel listModel;

    /**
     * Creates new form LogicalContextList
     */
    public ListPanelSituation(DefaultComboBoxModel listModel) {
        this.listModel = listModel;
        
        initComponents();
    }

    public DefaultComboBoxModel getListModel() {
        return listModel;
    }

    public JList getJListSituation() {
        return lstSituationList;
    }

    public JScrollPane getSpSituationList() {
        return spSituationList;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        spSituationList = new javax.swing.JScrollPane();
        lstSituationList = new javax.swing.JList();

        setLayout(new java.awt.BorderLayout());

        lstSituationList.setModel(listModel);
        lstSituationList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);
        lstSituationList.setCellRenderer(new MyListCellRenderer());
        spSituationList.setViewportView(lstSituationList);

        add(spSituationList, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList lstSituationList;
    private javax.swing.JScrollPane spSituationList;
    // End of variables declaration//GEN-END:variables
}
