/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.logicalcontextsimulator.gui.panel.contextList;

import javax.swing.DefaultComboBoxModel;
import javax.swing.JList;
import javax.swing.JScrollPane;

import com.logicalcontextsimulator.model.renderer.MyListCellRenderer;

/**
 *
 * @author MHL
 */
public class ListPanelLogicalContext extends javax.swing.JPanel {

    /**
	 * 
	 */
	private static final long serialVersionUID = 8894935138860511482L;
	private DefaultComboBoxModel listModel;
    
    /**
     * Creates new form LogicalContextList
     */
    public ListPanelLogicalContext(DefaultComboBoxModel model) {
        if(model == null){
          listModel = new DefaultComboBoxModel();
        }else{
          listModel = model;  
        }
        initComponents();
    }

    public JList getJListLogicalContext() {
        return jLogicalContextList;
    }

    public JScrollPane getSpLogicalContextList() {
        return spLogicalContextList; 
    }

    public DefaultComboBoxModel getListModel() {
        return listModel;
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        spLogicalContextList = new javax.swing.JScrollPane();
        jLogicalContextList = new javax.swing.JList();

        setLayout(new java.awt.BorderLayout());

        jLogicalContextList.setModel(listModel);
        jLogicalContextList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);
        jLogicalContextList.setCellRenderer(new MyListCellRenderer());
        spLogicalContextList.setViewportView(jLogicalContextList);

        add(spLogicalContextList, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList jLogicalContextList;
    private javax.swing.JScrollPane spLogicalContextList;
    // End of variables declaration//GEN-END:variables
}
