/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.logicalcontextsimulator.gui.panel.contextList;

import com.logicalcontextsimulator.model.renderer.ContextListItem;
import com.logicalcontextsimulator.model.renderer.MyListIconCellRenderer;
import com.logicalcontextsimulator.model.renderer.MyPhysicalContextListModel;
import com.logicalcontextsimulator.util.Constants;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JList;

/**
 *
 * @author MHL
 */
public class ListPanelPhysicalContext extends javax.swing.JPanel {

    /**
	 * 
	 */
	private static final long serialVersionUID = -6370512445516869986L;
	private MyPhysicalContextListModel listModel;
    
    /**
     * Creates new form ContextSourcesListPanel
     */
    public ListPanelPhysicalContext(MyPhysicalContextListModel listModel) {
        this.listModel = listModel;
        
        initComponents();
    }

    public JList getJListContextSource() {
        return jList1;
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();

        setLayout(new java.awt.BorderLayout());

        jList1.setModel(listModel);
        jList1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);
        jList1.setCellRenderer(new com.logicalcontextsimulator.model.renderer.MyListIconCellRenderer());
        jScrollPane1.setViewportView(jList1);

        add(jScrollPane1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList jList1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
