/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.logicalcontextsimulator.gui.panel.cardPanels;

import javax.swing.DefaultComboBoxModel;
import javax.swing.JComboBox;
import javax.swing.JPanel;

/**
 *
 * @author MHL
 */
public class CardPhysicalPanel extends javax.swing.JPanel {

    /**
	 * 
	 */
	private static final long serialVersionUID = -3355669876801101402L;

	private DefaultComboBoxModel listModelSituationGroup;
    
    private DefaultComboBoxModel listModelSituation;
    
    /**
     * Creates new form cardSituationPanel
     */
    public CardPhysicalPanel() {
        this.listModelSituationGroup = listModelSituationGroup;
       
        this.listModelSituation = listModelSituation;
        
        if(listModelSituation == null){
            this.listModelSituation = new DefaultComboBoxModel();
        }
        
        if(listModelSituationGroup == null){
            this.listModelSituationGroup = new DefaultComboBoxModel();
        }
        
        initComponents();
    } 

    public JComboBox getCbPhysicalContext() {
        return cbPhysicalContext;
    }

    public JPanel getPanelPhysical() {
        return panelPhysical;
    }
    
    
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelPhysical = new javax.swing.JPanel();
        cbPhysicalContext = new javax.swing.JComboBox();

        setLayout(new java.awt.BorderLayout());

        panelPhysical.setMinimumSize(new java.awt.Dimension(800, 800));
        panelPhysical.setPreferredSize(new java.awt.Dimension(150, 27));
        panelPhysical.setLayout(new java.awt.BorderLayout());

        cbPhysicalContext.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "All", "Location", "Time", "Individual", "Device", "Virtual", "Relation" }));
        panelPhysical.add(cbPhysicalContext, java.awt.BorderLayout.SOUTH);

        add(panelPhysical, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cbPhysicalContext;
    private javax.swing.JPanel panelPhysical;
    // End of variables declaration//GEN-END:variables
}
